version: '3.8'

services:
  currency_converter:
    container_name: currencyconverter
    image: ${DOCKER_REGISTRY-}currency_converter
    build:
      context: .
      dockerfile: CurrencyConverterAPI/Dockerfile
    environment:
      - ApiConfiguration__CurrencyBallast=${CURRENCYBALLAST}
      - ResiliencePollicy__retryCount=${RETRYCOUNT}
      - ResiliencePollicy__exceptionsAllowedBeforeBreaking=${EXCEPTIONALLOWEDBEFOREBREAKING}
      - ResiliencePollicy__durationOfBreakInSeconds=${DURATIONOFBREAKINSECONDS}
      - Serilog__WriteTo__1__Args__serverUrl=${SEQSERVERURL}
      - Serilog__WriteTo__1__Args__apiKey=${SEQAPIKEY}
      - Redis__Host=${REDISHOST}
      - Redis__Port=${REDISPORT}
      - Redis__Password=${REDISPASS}
      - Redis__Database=${REDISDATABASE}
    ports:
      - "9000:5000"
    depends_on:
      - redis
    networks:
      - bravo-net
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
    healthcheck:
      test: curl --fail http://localhost:5000/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  seq:
    container_name: seq
    image: ecarvalh2020/bravo_seq:1.0
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINUSERNAME=${SEQADMINUSERNAME}
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=${SEQADMINPASSWORDHASH}
      - SEQ_FIRSTRUN_REQUIREAUTHTENTICATIONFORHTTPINGESTION=True
    ports:
      - "5341:80"
    networks:
      - bravo-net
    volumes: 
      - ./Seq/seq_data:/data
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
    healthcheck:
      test: curl --fail http://localhost/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  
  redis:
    container_name: redis
    image: redis
    command: redis-server --appendonly yes --requirepass ${REDISPASS}
    ports:
      - "6379:6379"
    networks:
      - bravo-net
    volumes: 
      - ./Redis/data:/data
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - REDIS_REPLICATION_MODE=master
  
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    command: 
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    networks:
      - bravo-net
    volumes: 
      - ./Prometheus/conf:/etc/prometheus
      - ./Prometheus/data:/prometheus
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure

networks:
  bravo-net:
    name: bravo-net
    driver: bridge